name: easy_linkedin_login
description: Library for login with LinkedIn OAuth V2 service. This library helps you to implement authorization with LinkedIn OAuth API's.
version: 2.0.1
homepage: https://github.com/imsujan276/easy_linkedin_login
repository: https://github.com/imsujan276/easy_linkedin_login
documentation:

environment:
  sdk: '>=2.19.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  meta: 1.9.1
  rxdart: ^0.27.7
  uuid: ^4.1.0
  webview_flutter: ^4.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/linked_in_logo.png
    - assets/linkedin-signin-button.png
